name: Deploy to Github Pages
on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: aplank14/github-actions-react-to-github-pages@added-caching
      with:
        path: build
        caching: true